### ISSUE TITLE
php that can manage multiple versions

### ISSUE THREAD

**Issue by renzbeltran** [voxpupuli/puppet-php#694] opened 2023-07-21 11:23 UTC
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.25
- Ruby: 2.3
- Distribution: Debian 11
- Module version: 8.2.0

## Request

Hello, on our server we have multiple php versions that we want to handle. The php configurations might have different configurations as we migrate to a newer version since we have different teams that are independent. We would like to have a php module that can manage different versions. The module does not seem to allow this, is it possible for you to modify the module to allow it ? 

Thank you in advance,
Renz

**Comment by kwisatz** [comment] 2023-11-03 15:59
Would close as duplicate of #448

**Comment by kenyon** [comment] 2023-11-03 21:09
Closing as a duplicate of #448.

**Closed by kenyon** 2023-11-03 21:09 UTC
Labels: enhancement, question
